"""AST-backed SQL policy used at both sides of the Wren planning boundary.

The sidecar receives SQL produced by an untrusted model.  A token scanner is
not sufficient here: PostgreSQL permits comments, dollar quoted strings, CTEs,
and nested expressions that can hide a second statement or a data-changing
operation.  This module therefore parses with sqlglot's PostgreSQL grammar and
checks the resulting tree.  The caller may additionally provide the physical
objects derived from the MDL manifest; when it does, every non-CTE table must
match that allowlist.

The module intentionally exposes only policy decisions and never includes the
submitted SQL in an exception message.  That keeps the same no-leak invariant
as the framed RPC boundary.
"""

from __future__ import annotations

import contextlib
import io
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from typing import Any

from sqlglot import exp, parse
from sqlglot.errors import ErrorLevel, ParseError, SqlglotError


class SqlPolicyError(ValueError):
    """Raised when SQL is not one bounded read-only PostgreSQL query."""


# Keep this set deliberately broader than the Wren default.  These functions
# can read files, reach another database, mutate session/backend state, leak
# server metadata, or deliberately consume unbounded time/resources.
DANGEROUS_FUNCTIONS = frozenset(
    {
        "current_setting",
        "set_config",
        "pg_sleep",
        "pg_sleep_for",
        "pg_sleep_until",
        "pg_cancel_backend",
        "pg_terminate_backend",
        "pg_reload_conf",
        "pg_read_file",
        "pg_read_binary_file",
        "pg_ls_dir",
        "pg_ls_logdir",
        "pg_ls_waldir",
        "pg_ls_tmpdir",
        "pg_ls_archive_statusdir",
        "pg_stat_file",
        "dblink",
        "dblink_connect",
        "dblink_connect_u",
        "dblink_exec",
        "dblink_get_connections",
        "lo_import",
        "lo_export",
        "lo_get",
        "lo_put",
        "pg_advisory_lock",
        "pg_advisory_xact_lock",
        "pg_advisory_unlock",
        "pg_advisory_unlock_all",
        "pg_try_advisory_lock",
        "pg_try_advisory_xact_lock",
        "pg_try_advisory_unlock",
        "nextval",
        "setval",
        "lastval",
        "txid_current",
        "txid_current_snapshot",
        "pg_current_xact_id",
        "pg_current_snapshot",
        "version",
        # DuckDB and connector reader functions can be emitted by a dialect
        # adapter even when the selected datasource is PostgreSQL.
        "read_csv",
        "read_csv_auto",
        "read_parquet",
        "read_json",
        "read_json_auto",
        "read_ndjson",
        "read_ndjson_auto",
        "read_json_objects",
        "read_text",
        "read_blob",
        "read_xlsx",
        "parquet_scan",
        "glob",
        "iceberg_scan",
        "delta_scan",
        "postgres_scan",
        "postgres_query",
        "mysql_scan",
        "mysql_query",
        "sqlite_scan",
        "sqlite_query",
        "sniff_csv",
        "st_read",
        "st_readosm",
        "st_read_meta",
        "parquet_metadata",
        "parquet_file_metadata",
        "parquet_kv_metadata",
        "parquet_schema",
        "iceberg_metadata",
        "iceberg_snapshots",
        "load_file",
        "url",
    }
)

# Functions commonly generated by Wren for analytics.  Unknown/anonymous
# functions are rejected, which prevents a user-defined function from being
# smuggled through the database even when it is not in DANGEROUS_FUNCTIONS.
# Keep this list conservative and extend only when a real Wren fixture proves
# that a safe built-in is required.
SAFE_FUNCTIONS = frozenset(
    {
        "abs",
        "approx_count_distinct",
        "array_agg",
        "array_to_string",
        "avg",
        "ceil",
        "ceiling",
        "cast",
        "coalesce",
        "concat",
        "concat_ws",
        "convert",
        "corr",
        "count",
        "count_if",
        "date_add",
        "date_diff",
        "date_part",
        "date_sub",
        "date_trunc",
        # sqlglot canonicalizes PostgreSQL DATE_TRUNC to this class name when
        # parsing the Wren-generated native statement.
        "timestamp_trunc",
        "timestamp_add",
        "timestamp_diff",
        "datediff",
        "day",
        "extract",
        "floor",
        "greatest",
        "ifnull",
        "ilike",
        "least",
        "lower",
        "ltrim",
        "max",
        "md5",
        "min",
        "nullif",
        "percentile_cont",
        "percentile_disc",
        "power",
        "regexp_extract",
        "regexp_replace",
        "repeat",
        "replace",
        "round",
        "rtrim",
        "sha256",
        "sign",
        "sin",
        "split_part",
        "sqrt",
        "stddev",
        "stddev_pop",
        "stddev_samp",
        "string_agg",
        "substr",
        "substring",
        "sum",
        "tan",
        "to_char",
        "to_date",
        "trim",
        "upper",
        "variance",
        "var_pop",
        "var_samp",
        "week",
        "year",
        "current_date",
        "current_time",
        "current_timestamp",
        "localtime",
        "localtimestamp",
        "row_number",
        "rank",
        "dense_rank",
        "percent_rank",
        "cume_dist",
        "ntile",
        "lag",
        "lead",
        "first_value",
        "last_value",
        "nth_value",
        "json_extract",
        "json_extract_path",
        "json_extract_path_text",
        "jsonb_extract_path",
        "jsonb_extract_path_text",
        "jsonb_build_object",
        "json_build_object",
        "json_object_agg",
        "jsonb_object_agg",
        "count_star",
    }
)

# AST classes that are never valid in a read-only query.  Names are used in
# addition to isinstance so the policy remains compatible with sqlglot
# versions that rename or do not expose a dialect-specific class (COPY/CALL
# are examples).  A DML nested inside a CTE is caught by walking the tree.
_DENIED_EXPRESSION_NAMES = frozenset(
    {
        "Alter",
        "Analyze",
        "Attach",
        "Call",
        "Command",
        "Commit",
        "Copy",
        "Create",
        "Delete",
        "Describe",
        "Detach",
        "Drop",
        "Grant",
        "Insert",
        "Into",
        "Lock",
        "Merge",
        "Prepare",
        "Refresh",
        "Release",
        "Rollback",
        "Set",
        "Show",
        "Transaction",
        "Truncate",
        "Update",
        "Use",
        "Vacuum",
        "Values",
    }
)

_QUERY_ROOT_NAMES = frozenset({"Select", "Union", "Intersect", "Except"})


@dataclass(frozen=True, slots=True)
class PhysicalTable:
    """One physical table permitted by the MDL manifest."""

    catalog: str | None
    schema: str | None
    table: str

    def normalized(self) -> tuple[str | None, str | None, str]:
        return (
            self.catalog.lower() if self.catalog else None,
            self.schema.lower() if self.schema else None,
            self.table.lower(),
        )


@dataclass(frozen=True, slots=True)
class PhysicalAllowlist:
    """Canonical physical schema/table allowlist for native SQL checks."""

    tables: frozenset[PhysicalTable]

    @property
    def schemas(self) -> frozenset[str]:
        return frozenset(item.schema.lower() for item in self.tables if item.schema)

    @property
    def catalogs(self) -> frozenset[str]:
        return frozenset(item.catalog.lower() for item in self.tables if item.catalog)

    def as_dict(self) -> dict[str, Any]:
        table_rows = [
            {
                **({"catalog": item.catalog} if item.catalog else {}),
                **({"schema": item.schema} if item.schema else {}),
                "table": item.table,
            }
            for item in sorted(
                self.tables,
                key=lambda value: (
                    (value.catalog or "").lower(),
                    (value.schema or "").lower(),
                    value.table.lower(),
                ),
            )
        ]
        return {
            "catalogs": sorted(self.catalogs),
            "schemas": sorted(self.schemas),
            "tables": table_rows,
        }


def _parse_one_read_only(sql: str) -> exp.Expression:
    if not isinstance(sql, str) or not sql.strip():
        raise SqlPolicyError("query is empty")
    try:
        # parse(), unlike parse_one(), lets us reject a second statement
        # instead of silently ignoring it.  PostgreSQL handles comments and
        # dollar-quoted literals before the AST is produced.
        # Some sqlglot dialect fallbacks print an unsupported-syntax warning
        # containing the submitted SQL.  Suppress that diagnostic at this
        # boundary: SQL (and especially literal secrets) must never reach the
        # sidecar's stderr logs either.
        with contextlib.redirect_stderr(io.StringIO()):
            statements = parse(sql, read="postgres", error_level=ErrorLevel.RAISE)
    except (ParseError, SqlglotError, ValueError, TypeError) as exc:
        raise SqlPolicyError("query is not valid PostgreSQL SQL") from exc
    # sqlglot represents a trailing semicolon followed by a comment as a
    # standalone ``Semicolon`` node, and an empty trailing statement as None.
    # Those do not constitute a second executable statement.  Any additional
    # query/command node still fails closed.
    executable = [
        item
        for item in statements
        if item is not None and type(item).__name__ != "Semicolon"
    ]
    if len(executable) != 1:
        raise SqlPolicyError("multiple SQL statements are not allowed")
    statement = executable[0]
    if type(statement).__name__ not in _QUERY_ROOT_NAMES:
        raise SqlPolicyError("only SELECT or read-only query expressions are allowed")
    for node in statement.walk():
        if type(node).__name__ in _DENIED_EXPRESSION_NAMES:
            raise SqlPolicyError("query contains a denied SQL operation")
    return statement


def validate_semantic_sql(sql: str) -> str:
    """Type-check semantic SQL as one read-only PostgreSQL query."""

    _parse_one_read_only(sql)
    return sql.strip()


def _function_name(function: exp.Func) -> str:
    """Return the canonical lower-case function name for a sqlglot node."""

    if isinstance(function, exp.Anonymous):
        value = function.name
    else:
        try:
            value = function.sql_name()
        except (AttributeError, TypeError):
            value = function.name
    if not isinstance(value, str) or not value:
        value = type(function).__name__
    return value.lower()


def _check_functions(statement: exp.Expression) -> None:
    for function in statement.find_all(exp.Func):
        # sqlglot models boolean connectors (AND/OR) as Func subclasses for
        # inheritance purposes, but they are operators, not callable database
        # functions and therefore must not be looked up in the function list.
        if isinstance(function, (exp.Connector, exp.Case, exp.If, exp.Explode, exp.Unnest)):
            continue
        name = _function_name(function)
        if name in DANGEROUS_FUNCTIONS or name not in SAFE_FUNCTIONS:
            raise SqlPolicyError("query contains a function outside the allowlist")


def _cte_names(statement: exp.Expression) -> set[str]:
    names: set[str] = set()
    for cte in statement.find_all(exp.CTE):
        alias = cte.alias_or_name
        if isinstance(alias, str) and alias:
            names.add(alias.lower())
    return names


def _identifier_quoted(identifier: Any) -> bool:
    return bool(getattr(identifier, "quoted", False))


def _identifier_value(identifier: Any) -> str:
    value = getattr(identifier, "name", None)
    if isinstance(value, str):
        return value
    value = getattr(identifier, "this", identifier)
    return value if isinstance(value, str) else str(value)


def _table_parts(table: exp.Table) -> tuple[str, str | None, str | None, bool]:
    identifier = table.this
    name = _identifier_value(identifier)
    db = table.args.get("db")
    catalog = table.args.get("catalog")
    schema = _identifier_value(db) if db is not None else None
    catalog_name = _identifier_value(catalog) if catalog is not None else None
    return name, schema, catalog_name, _identifier_quoted(identifier)


def _table_matches(
    table: exp.Table,
    allowlist: PhysicalAllowlist,
) -> bool:
    name, schema, catalog, quoted = _table_parts(table)
    if not name:
        return False
    lower_name = name.lower()
    lower_schema = schema.lower() if schema else None
    lower_catalog = catalog.lower() if catalog else None
    for allowed in allowlist.tables:
        ac, ass, at = allowed.normalized()
        if at != lower_name:
            continue
        # Never let an unqualified name select an arbitrary same-named table
        # through PostgreSQL's search_path.  Wren manifests normally carry a
        # physical schema and the native plan must preserve that qualification.
        # A schema-less allowlist entry is retained only for explicit injected
        # seams whose MDL truly has no schema to authorize.
        if ass is not None and lower_schema is None:
            continue
        if lower_schema is not None and ass != lower_schema:
            continue
        if lower_catalog is not None and ac != lower_catalog:
            continue
        # Quoted identifiers are case-sensitive in PostgreSQL.  Unquoted
        # identifiers are case-folded; the normalized comparison above is the
        # safe match for generated SQL, while this exact check prevents a
        # quoted typo from being treated as the unquoted object.
        if quoted and name != allowed.table:
            continue
        if schema is not None and _identifier_quoted(table.args.get("db")):
            if schema != allowed.schema:
                continue
        if catalog is not None and _identifier_quoted(table.args.get("catalog")):
            if catalog != allowed.catalog:
                continue
        return True
    return False


def _check_tables(statement: exp.Expression, allowlist: PhysicalAllowlist) -> None:
    ctes = _cte_names(statement)
    ctes_lower = {item.lower() for item in ctes}
    for table in statement.find_all(exp.Table):
        name, schema, catalog, quoted = _table_parts(table)
        # A CTE is an in-memory query result, not a physical object.  A schema
        # or catalog qualifier can never be a CTE reference and is therefore
        # not exempted.
        cte_match = name in ctes if quoted else name.lower() in ctes_lower
        if not schema and not catalog and cte_match:
            continue
        if not _table_matches(table, allowlist):
            raise SqlPolicyError("query references an object outside the MDL allowlist")


def validate_native_sql(
    sql: str,
    *,
    allowed_physical: PhysicalAllowlist | Mapping[str, Any] | None = None,
) -> str:
    """Validate native SQL structurally and against permitted physical tables.

    ``allowed_physical`` is required by the production Wren adapter.  It is
    optional only for injected planner seams, where callers can still obtain
    AST read-only/function checks.  An explicit empty allowlist is fail-closed.
    """

    statement = _parse_one_read_only(sql)
    _check_functions(statement)
    if allowed_physical is not None:
        allowlist = (
            allowed_physical
            if isinstance(allowed_physical, PhysicalAllowlist)
            else physical_allowlist_from_dict(allowed_physical)
        )
        _check_tables(statement, allowlist)
    return sql.strip()


def physical_allowlist_from_dict(value: Mapping[str, Any]) -> PhysicalAllowlist:
    """Parse the JSON-safe ``allowedPhysical`` representation fail-closed."""

    raw_tables = value.get("tables")
    if not isinstance(raw_tables, (list, tuple)):
        return PhysicalAllowlist(frozenset())
    tables: set[PhysicalTable] = set()
    for raw in raw_tables:
        if not isinstance(raw, Mapping):
            continue
        table = raw.get("table")
        schema = raw.get("schema")
        catalog = raw.get("catalog")
        if not isinstance(table, str) or not table or len(table) > 512:
            continue
        if schema is not None and (not isinstance(schema, str) or not schema):
            continue
        if catalog is not None and (not isinstance(catalog, str) or not catalog):
            continue
        tables.add(PhysicalTable(catalog, schema, table))
    return PhysicalAllowlist(frozenset(tables))


def physical_allowlist_from_manifest(manifest: Mapping[str, Any]) -> PhysicalAllowlist:
    """Derive physical source objects from a Wren JSON MDL manifest."""

    default_catalog = manifest.get("catalog")
    if not isinstance(default_catalog, str) or not default_catalog:
        default_catalog = None
    default_schema = manifest.get("schema")
    if not isinstance(default_schema, str) or not default_schema:
        default_schema = None
    raw_models = manifest.get("models")
    tables: set[PhysicalTable] = set()
    if not isinstance(raw_models, (list, tuple)):
        return PhysicalAllowlist(frozenset())
    for model in raw_models:
        if not isinstance(model, Mapping):
            continue
        ref = model.get("tableReference", model.get("table_reference"))
        if not isinstance(ref, Mapping):
            continue
        table = ref.get("table")
        schema = ref.get("schema", default_schema)
        catalog = ref.get("catalog", ref.get("database", default_catalog))
        if not isinstance(table, str) or not table:
            continue
        if schema is not None and not isinstance(schema, str):
            schema = None
        if catalog is not None and not isinstance(catalog, str):
            catalog = None
        tables.add(PhysicalTable(catalog, schema, table))
    return PhysicalAllowlist(frozenset(tables))


def extract_table_names(sql: str) -> frozenset[str]:
    """Return unqualified table/CTE names for injected planner compatibility."""

    statement = _parse_one_read_only(sql)
    return frozenset(
        name
        for name, schema, catalog, _quoted in (
            _table_parts(table) for table in statement.find_all(exp.Table)
        )
        if name and not schema and not catalog
    )


# Backwards-compatible import name used by older focused tests and adapters.
validate_read_only_sql = validate_native_sql
