import i18n from "i18next";
import { initReactI18next } from "react-i18next";

export type ConsoleLocale = "en-US" | "zh-CN";

const resources = {
  "en-US": {
    translation: {
      brand: { name: "DSH Data Agent", subtitle: "Semantic Console" },
      common: {
        cancel: "Cancel", close: "Close", save: "Save", refresh: "Refresh", loading: "Loading…",
        draft: "Draft", published: "Published", tracked: "Tracked", source: "Source", diff: "Diff",
        connected: "Connected", unavailable: "API unavailable", current: "Current", readOnly: "Read only",
        yes: "Yes", no: "No", visible: "Visible", hidden: "Hidden", optional: "Optional", required: "Required",
        unknown: "Unknown", none: "None", columns: "columns", files: "files", detected: "detected",
        closeDialog: "Close dialog", switchToDark: "Switch to dark theme", switchToLight: "Switch to light theme",
        openHistory: "Open version history", signedIn: "Signed in as WS",
      },
      nav: {
        workspace: "Workspace", overview: "Overview", datasources: "Data sources", schema: "Schema browser",
        semanticLayer: "Semantic layer", models: "Models", relationships: "Relationships", views: "Views",
        cubes: "Cubes", rules: "Business rules", sqlKnowledge: "SQL knowledge", instructions: "Instructions", mdl: "MDL source", settings: "Settings", helpTitle: "Need a hand?",
        helpBody: "Read the semantic layer guide", project: "PROJECT", close: "Close navigation", open: "Open navigation",
      },
      page: {
        overview: "Overview", datasources: "Data sources", schema: "Schema browser", models: "Models",
        relationships: "Relationships", views: "Views", cubes: "Cubes", rules: "Business rules", sqlKnowledge: "SQL knowledge", instructions: "Instructions", mdl: "MDL source",
      },
      model: {
        eyebrow: "Semantic layer", title: "Business models", pageDescription: "Shape the business language around your source tables, then publish it as one reliable semantic layer.",
        searchPlaceholder: "Search models", modelCount: "{{count}} models", noModels: "No business models",
        noModelsBody: "Import a table from Schema browser or import an existing project to create a model.",
        modelDetails: "Model details", modelDetailsHint: "Business metadata is kept beside the source identity.",
        technicalName: "Technical name", sourceFile: "Source file", schema: "Schema", table: "Table",
        businessDomain: "Business domain", primaryKey: "Primary key", modelVisible: "Visible to query users",
        bilingualName: "Business name", bilingualDescription: "Description", chinese: "中文", english: "English",
        fields: "Field dictionary", fieldCount: "{{count}} fields", fieldSearch: "Filter fields",
        field: "Field", type: "Type", role: "Semantic role", format: "Format", expression: "Expression",
        description: "Description", displayName: "Display name", visible: "Visible", notNull: "Non-null",
        calculated: "Calculated", auto: "Auto", dimension: "Dimension", measure: "Measure", time: "Time", key: "Key",
        currency: "Currency", number: "Number", percentage: "Percentage", date: "Date", saveDraft: "Save draft",
        saved: "Draft saved", saveError: "Draft save failed", sourceView: "Source", diffView: "Diff",
        sourceHint: "Underlying files remain visible for review. Switch to source editing in MDL source.",
        diffHint: "Published versus draft changes for this model.", noDiff: "No unpublished changes", noDiffBody: "The current model matches its published file.",
        modelSaved: "Business model saved", modelSaveBody: "The visual changes are now a project draft.",
        sourceUnavailable: "Source file unavailable", sourceUnavailableBody: "The semantic project did not return this source file.",
        externalChangeTitle: "This model changed on the server", externalChangeBody: "Your local draft is still intact. Save it to overwrite the server version, or reload the server version.", useServerVersion: "Use server version",
      },
      relationshipSource: {
        source: "Source", diff: "Diff", file: "Relationship source", openEditor: "Open in source editor",
        sourceHint: "Review the Wren relationship definition generated by the visual editor.",
        diffHint: "Review unpublished relationship changes against the published version.",
        unavailable: "The relationship source file is unavailable.", noDiff: "No unpublished relationship changes",
      },
      relationship: {
        title: "Relationships", description: "Connect business models at field level and maintain the Wren definition in the same workspace.",
        views: "Relationship views", graphTab: "Relationship map", sourceTab: "Source", diffTab: "Changes",
        modelCount: "{{count}} models", relationCount: "{{count}} relationships",
      },
      status: {
        offlineTitle: "Semantic Console is offline", offlineBody: "Could not load {{items}}. No local project data was substituted.",
        validationPassed: "Validation passed", validationNeedsAttention: "Validation needs attention", publishFailed: "Publish failed",
        projectPublished: "Project published", draftSaved: "Draft saved", draftSafe: "Your semantic project is safe to continue editing.", sourceReadFailed: "Could not read project file",
      },
      action: { addDatasource: "Add data source", importSchema: "Import schema", viewModels: "View models", manage: "Manage", publish: "Publish", validate: "Validate" },
      language: { label: "Language", english: "English", chinese: "简体中文", switchTo: "Switch language" },
      empty: { noDataSources: "No data sources", noVersions: "No versions yet", noProjectFiles: "No project files", noFileSelected: "No file selected" },
    },
  },
  "zh-CN": {
    translation: {
      brand: { name: "DSH Data Agent", subtitle: "语义控制台" },
      common: {
        cancel: "取消", close: "关闭", save: "保存", refresh: "刷新", loading: "加载中…",
        draft: "草稿", published: "已发布", tracked: "已跟踪", source: "源文件", diff: "差异",
        connected: "已连接", unavailable: "API 不可用", current: "当前", readOnly: "只读",
        yes: "是", no: "否", visible: "可见", hidden: "隐藏", optional: "可选", required: "必填",
        unknown: "未知", none: "无", columns: "列", files: "文件", detected: "已检测",
        closeDialog: "关闭对话框", switchToDark: "切换到深色主题", switchToLight: "切换到浅色主题",
        openHistory: "打开版本历史", signedIn: "当前用户 WS",
      },
      nav: {
        workspace: "工作区", overview: "概览", datasources: "数据源", schema: "Schema 浏览器",
        semanticLayer: "语义层", models: "业务模型", relationships: "关系", views: "视图",
        cubes: "指标立方体", rules: "业务规则", sqlKnowledge: "SQL 知识", instructions: "指令", mdl: "MDL 源文件", settings: "设置", helpTitle: "需要帮助？",
        helpBody: "阅读语义层指南", project: "项目", close: "关闭导航", open: "打开导航",
      },
      page: {
        overview: "概览", datasources: "数据源", schema: "Schema 浏览器", models: "业务模型",
        relationships: "关系", views: "视图", cubes: "指标立方体", rules: "业务规则", sqlKnowledge: "SQL 知识", instructions: "指令", mdl: "MDL 源文件",
      },
      model: {
        eyebrow: "语义层", title: "业务模型", pageDescription: "围绕源表定义业务语言，并将其发布为可靠的统一语义层。",
        searchPlaceholder: "搜索模型", modelCount: "{{count}} 个模型", noModels: "暂无业务模型",
        noModelsBody: "请从 Schema 浏览器导入表，或导入已有项目来创建模型。",
        modelDetails: "模型信息", modelDetailsHint: "业务元数据与底层数据源标识分开维护。",
        technicalName: "技术名称", sourceFile: "源文件", schema: "Schema", table: "表",
        businessDomain: "业务域", primaryKey: "主键", modelVisible: "对查询用户可见",
        bilingualName: "业务名称", bilingualDescription: "描述", chinese: "中文", english: "英文",
        fields: "字段数据字典", fieldCount: "{{count}} 个字段", fieldSearch: "筛选字段",
        field: "字段", type: "类型", role: "语义角色", format: "格式", expression: "表达式",
        description: "描述", displayName: "显示名称", visible: "可见", notNull: "非空",
        calculated: "计算字段", auto: "自动", dimension: "维度", measure: "度量", time: "时间", key: "键",
        currency: "货币", number: "数值", percentage: "百分比", date: "日期", saveDraft: "保存草稿",
        saved: "草稿已保存", saveError: "草稿保存失败", sourceView: "源文件", diffView: "差异",
        sourceHint: "底层文件始终可查看。如需编辑源文件，请前往 MDL 源文件页面。", diffHint: "查看此模型的已发布版本与草稿差异。",
        noDiff: "没有未发布的变更", noDiffBody: "当前模型与已发布文件一致。", modelSaved: "业务模型已保存", modelSaveBody: "可视化修改已保存为项目草稿。",
        sourceUnavailable: "源文件不可用", sourceUnavailableBody: "语义项目没有返回该模型的源文件。",
        externalChangeTitle: "此模型已在服务器上发生变化", externalChangeBody: "本地草稿仍然保留。保存可覆盖服务器版本，也可以重新加载服务器版本。", useServerVersion: "使用服务器版本",
      },
      relationshipSource: {
        source: "源文件", diff: "差异", file: "关系源文件", openEditor: "在源文件编辑器中打开",
        sourceHint: "查看可视化编辑器生成的 Wren 关系定义。", diffHint: "对比关系草稿与已发布版本的差异。",
        unavailable: "关系源文件不可用。", noDiff: "没有未发布的关系变更",
      },
      relationship: {
        title: "关系", description: "在字段级连接业务模型，并在同一工作区维护 Wren 关系定义。",
        views: "关系视图", graphTab: "关系图", sourceTab: "源文件", diffTab: "变更",
        modelCount: "{{count}} 个模型", relationCount: "{{count}} 条关系",
      },
      status: {
        offlineTitle: "语义控制台离线", offlineBody: "无法加载 {{items}}，未使用本地模拟数据。",
        validationPassed: "校验通过", validationNeedsAttention: "校验需要处理", publishFailed: "发布失败",
        projectPublished: "项目已发布", draftSaved: "草稿已保存", draftSafe: "语义项目已安全保存，可以继续编辑。", sourceReadFailed: "无法读取项目文件",
      },
      action: { addDatasource: "添加数据源", importSchema: "导入 Schema", viewModels: "查看模型", manage: "管理", publish: "发布", validate: "校验" },
      language: { label: "语言", english: "English", chinese: "简体中文", switchTo: "切换语言" },
      empty: { noDataSources: "暂无数据源", noVersions: "暂无版本", noProjectFiles: "暂无项目文件", noFileSelected: "未选择文件" },
    },
  },
} as const;

/**
 * Compatibility translations for the existing console surfaces. New screens
 * should use namespaced i18next keys directly; this map lets the shared UI
 * primitives localize legacy labels while those screens are incrementally
 * migrated.
 */
const legacyTranslations: Record<string, string> = {
  "Overview": "概览", "Data sources": "数据源", "Schema browser": "Schema 浏览器", "Models": "业务模型",
  "Relationships": "关系", "Views": "视图", "Instructions": "指令", "MDL source": "MDL 源文件",
  "Workspace": "工作区", "Semantic layer": "语义层", "Settings": "设置", "Need a hand?": "需要帮助？",
  "Read the semantic layer guide": "阅读语义层指南", "Close": "关闭", "Cancel": "取消", "Save": "保存",
  "Refresh": "刷新", "Validate": "校验", "Publish": "发布", "Restore": "恢复", "Current": "当前",
  "Connected": "已连接", "API unavailable": "API 不可用", "Published": "已发布", "Draft changes": "草稿变更",
  "Draft": "草稿", "Tracked": "已跟踪", "Read only": "只读", "Open source": "打开源文件", "Source file": "源文件",
  "No activity yet": "暂无活动", "No data sources": "暂无数据源", "No versions yet": "暂无版本", "No project files": "暂无项目文件",
  "No model files": "暂无模型文件", "No relationship files": "暂无关系文件", "No view files": "暂无视图文件",
  "No instruction file": "暂无指令文件", "No file selected": "未选择文件", "No file loaded": "未加载文件",
  "Select a data source": "选择数据源", "Select a schema": "选择 Schema", "Select a table": "选择表",
  "Tables and views": "表和视图", "Columns": "列", "Schemas": "Schema", "Filter tables": "筛选表",
  "Import selected table": "导入所选表", "Import table": "导入表", "Import project": "导入项目",
  "Add data source": "添加数据源", "Add the first source": "添加第一个数据源", "Manage data sources": "管理数据源",
  "Save data source": "保存数据源", "Test connection": "测试连接", "Set as current": "设为当前",
  "Edit": "编辑", "Test": "测试", "Choose a data source": "选择数据源", "Choose an option": "选择选项",
  "No schema metadata": "暂无 Schema 元数据", "No tables found": "未找到表",
  "Project history": "项目历史", "Version history": "版本历史", "Review history": "查看历史", "All versions": "全部版本",
  "Save instructions": "保存指令", "Save source": "保存源文件", "Project files": "项目文件", "Semantic source": "语义源",
  "Plain text editor": "纯文本编辑器", "No models": "暂无模型", "No relationships": "暂无关系",
  "Connection healthy": "连接正常", "Connection test failed": "连接测试失败", "Connection not tested": "尚未测试连接",
  "Secrets protected": "密钥已保护", "Connection details": "连接详情",
  "Validation passed": "校验通过", "Validation needs attention": "校验需要处理", "Project published": "项目已发布",
  "Publish failed": "发布失败", "Draft saved": "草稿已保存", "Draft save failed": "草稿保存失败",
  "Could not read project file": "无法读取项目文件", "Semantic Console is offline": "语义控制台离线",
  "Not available": "不可用",
};

const savedLocale = typeof localStorage === "undefined" ? undefined : localStorage.getItem("semantic-console-locale");

void i18n.use(initReactI18next).init({
  resources,
  lng: savedLocale === "zh-CN" ? "zh-CN" : "en-US",
  fallbackLng: "en-US",
  interpolation: { escapeValue: false },
  returnNull: false,
});

export function setConsoleLocale(locale: ConsoleLocale) {
  if (typeof localStorage !== "undefined") localStorage.setItem("semantic-console-locale", locale);
  void i18n.changeLanguage(locale);
}

/** Translate an existing literal UI label without changing persisted values. */
export function translateLegacy(value: string): string {
  return i18n.language === "zh-CN" ? legacyTranslations[value] ?? value : value;
}

export { i18n };
export default i18n;
