"""Public API for the Wren data-agent sidecar boundary."""

from .dispatch import (
    RPC_METHODS,
    ContextProvider,
    Dispatcher,
    ProjectValidator,
    QueryPlanner,
    QueryService,
    RpcDispatcher,
    RpcRequest,
    SidecarDependencies,
    dispatch_request,
)
from .errors import RpcError, RpcFault
from .protocol import (
    DEFAULT_MAX_FRAME_BYTES,
    PROTOCOL_VERSION,
    FramingError,
    ProtocolError,
    decode_frame,
    decode_payload,
    encode_frame,
    read_frame,
    write_frame,
)
from .server import JsonRpcServer, serve
from .query import (
    MAX_QUERY_CONCURRENCY,
    MAX_PREVIEW_BYTES,
    MAX_PREVIEW_ROWS,
    MAX_QUERY_ROWS,
    MAX_TIMEOUT_MS,
    PostgresQueryExecutor,
    QueryLimits,
    SqlPolicyError,
    WrenQueryService,
    validate_native_sql,
    validate_read_only_sql,
    validate_semantic_sql,
)
from .sql_policy import DANGEROUS_FUNCTIONS, PhysicalAllowlist, PhysicalTable
from .wren_adapter import (
    WREN_PACKAGE_NAME,
    WREN_SUPPORTED_VERSION,
    LazyWrenAdapter,
    WrenAdapter,
    default_dependencies,
)

__all__ = [
    "DEFAULT_MAX_FRAME_BYTES",
    "ContextProvider",
    "Dispatcher",
    "FramingError",
    "JsonRpcServer",
    "PROTOCOL_VERSION",
    "RPC_METHODS",
    "ProjectValidator",
    "QueryPlanner",
    "QueryService",
    "ProtocolError",
    "RpcDispatcher",
    "RpcError",
    "RpcFault",
    "RpcRequest",
    "SidecarDependencies",
    "decode_frame",
    "decode_payload",
    "dispatch_request",
    "encode_frame",
    "read_frame",
    "serve",
    "write_frame",
    "WREN_PACKAGE_NAME",
    "WREN_SUPPORTED_VERSION",
    "LazyWrenAdapter",
    "WrenAdapter",
    "default_dependencies",
    "MAX_PREVIEW_BYTES",
    "MAX_PREVIEW_ROWS",
    "MAX_QUERY_ROWS",
    "MAX_QUERY_CONCURRENCY",
    "MAX_TIMEOUT_MS",
    "PostgresQueryExecutor",
    "QueryLimits",
    "SqlPolicyError",
    "WrenQueryService",
    "validate_read_only_sql",
    "validate_native_sql",
    "validate_semantic_sql",
    "DANGEROUS_FUNCTIONS",
    "PhysicalAllowlist",
    "PhysicalTable",
]
