"""Public API for the SemaRail sidecar boundary."""

from .dispatch import (
    RPC_METHODS,
    ContextProvider,
    Dispatcher,
    ProjectValidator,
    QueryPlanner,
    QueryService,
    RpcDispatcher,
    RpcRequest,
    SidecarDependencies,
    dispatch_request,
)
from .errors import RESULT_TOO_LARGE, RpcError, RpcFault
from .protocol import (
    DEFAULT_MAX_FRAME_BYTES,
    PROTOCOL_VERSION,
    FramingError,
    ProtocolError,
    decode_frame,
    decode_payload,
    encode_frame,
    read_frame,
    write_frame,
)
from .server import JsonRpcServer, serve
from .query import (
    MAX_QUERY_CONCURRENCY,
    MAX_PREVIEW_BYTES,
    MAX_PREVIEW_ROWS,
    MAX_QUERY_ROWS,
    MAX_TIMEOUT_MS,
    ARTIFACT_FORMAT,
    MAX_ARTIFACT_BYTES,
    MAX_ARTIFACT_INLINE_BYTES,
    MAX_ARTIFACT_INLINE_ROWS,
    MAX_ARTIFACT_PREVIEW_ROWS,
    ArtifactRequest,
    PostgresQueryExecutor,
    QueryLimits,
    SqlPolicyError,
    WrenQueryService,
    validate_native_sql,
    validate_read_only_sql,
    validate_semantic_sql,
    artifact_request_from_mapping,
)
from .sql_policy import DANGEROUS_FUNCTIONS, PhysicalAllowlist, PhysicalTable
from .semantic_service import (
    MAX_QUESTION_CHARS,
    MAX_SEMANTIC_SQL_CHARS,
    MAX_SEMANTIC_RESULT_BYTES,
    SEMANTIC_SCHEMA_VERSION,
    SemanticRuntime,
    SemanticService,
)
from .wren_adapter import (
    WREN_PACKAGE_NAME,
    WREN_SUPPORTED_VERSION,
    LazyWrenAdapter,
    WrenAdapter,
    default_dependencies,
)

__all__ = [
    "DEFAULT_MAX_FRAME_BYTES",
    "ContextProvider",
    "Dispatcher",
    "FramingError",
    "JsonRpcServer",
    "PROTOCOL_VERSION",
    "RPC_METHODS",
    "ProjectValidator",
    "QueryPlanner",
    "QueryService",
    "ProtocolError",
    "RpcDispatcher",
    "RpcError",
    "RpcFault",
    "RESULT_TOO_LARGE",
    "RpcRequest",
    "SidecarDependencies",
    "decode_frame",
    "decode_payload",
    "dispatch_request",
    "encode_frame",
    "read_frame",
    "serve",
    "write_frame",
    "WREN_PACKAGE_NAME",
    "WREN_SUPPORTED_VERSION",
    "LazyWrenAdapter",
    "WrenAdapter",
    "default_dependencies",
    "MAX_PREVIEW_BYTES",
    "MAX_PREVIEW_ROWS",
    "MAX_QUERY_ROWS",
    "MAX_QUERY_CONCURRENCY",
    "MAX_TIMEOUT_MS",
    "ARTIFACT_FORMAT",
    "MAX_ARTIFACT_BYTES",
    "MAX_ARTIFACT_INLINE_BYTES",
    "MAX_ARTIFACT_INLINE_ROWS",
    "MAX_ARTIFACT_PREVIEW_ROWS",
    "ArtifactRequest",
    "artifact_request_from_mapping",
    "PostgresQueryExecutor",
    "QueryLimits",
    "SqlPolicyError",
    "WrenQueryService",
    "validate_read_only_sql",
    "validate_native_sql",
    "validate_semantic_sql",
    "DANGEROUS_FUNCTIONS",
    "PhysicalAllowlist",
    "PhysicalTable",
    "MAX_QUESTION_CHARS",
    "MAX_SEMANTIC_SQL_CHARS",
    "MAX_SEMANTIC_RESULT_BYTES",
    "SEMANTIC_SCHEMA_VERSION",
    "SemanticRuntime",
    "SemanticService",
]
